name: "CI Latest Release"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run make
        run: |
          make build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          draft: true
          title: "Development Build"
          files: |
            LICENSE.txt
            release/*